import { Roboto } from 'next/font/google'
import './globals.css'
import Header from '../components/layout/Header'
import Footer from '../components/layout/Footer'
import { SessionProvider } from 'next-auth/react'
import { AppProvider } from '../components/AppContext.js'

const roboto = Roboto({ subsets: ['latin'], weight:['400','500', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body   className='bg-background roboto.className' >        
        <main className='max-w-7xl mx-auto  p-4'>
          <AppProvider>
        <Header />
        {children}
        <Footer />
        </AppProvider>
        </main>
        </body>
    </html>
  )
}
